name: Cloud Functions Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Specify all desired python versions
        python-version: ["3.12"]

    steps:
      # Setup Runner with python
      - uses: actions/checkout@v4
      - run: cd functions/
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

        # Run all CI actions
      - name: Test with pytest
        run: |
          pip install pytest
          pytest